import { Student, DashboardMetrics, FilterState } from '../types/student';
import { calculateMetrics } from '../data/mockStudentData';

export interface AthenaSchemaObject {
  name: string;
  type: 'TABLE' | 'VIEW';
  description: string;
  sqlDefinition?: string;
  columns: { name: string; type: string; comment?: string }[];
}

export const ATHENA_OBJECTS: AthenaSchemaObject[] = [
  {
    name: 'student_raw',
    type: 'TABLE',
    description: 'Raw ingested student records from S3 data lake (CSV/Parquet format)',
    columns: [
      { name: 'school', type: 'varchar(10)', comment: 'School code: GP or MS' },
      { name: 'sex', type: 'varchar(2)', comment: 'Gender: F or M' },
      { name: 'age', type: 'int', comment: 'Student age in years' },
      { name: 'studytime', type: 'int', comment: 'Weekly study time: 1 (<2h) to 4 (>10h)' },
      { name: 'failures', type: 'int', comment: 'Number of past class failures' },
      { name: 'absences', type: 'int', comment: 'Number of school absences' },
      { name: 'G1', type: 'int', comment: 'First period grade (0-20)' },
      { name: 'G2', type: 'int', comment: 'Second period grade (0-20)' },
      { name: 'G3', type: 'int', comment: 'Final grade (0-20)' },
    ],
  },
  {
    name: 'student_analytics',
    type: 'TABLE',
    description: 'Enriched analytical dataset with categorized features and standardized metrics',
    columns: [
      { name: 'student_id', type: 'varchar(20)' },
      { name: 'school', type: 'varchar(10)' },
      { name: 'sex', type: 'varchar(2)' },
      { name: 'age', type: 'int' },
      { name: 'studytime', type: 'int' },
      { name: 'absences', type: 'int' },
      { name: 'G1', type: 'int' },
      { name: 'G2', type: 'int' },
      { name: 'G3', type: 'int' },
      { name: 'performance_level', type: 'varchar(15)', comment: 'High (>=15), Medium (10-14), Low (<10)' },
      { name: 'absence_group', type: 'varchar(20)', comment: 'Low (0-4), Moderate (5-9), High (10+)' },
      { name: 'pass_status', type: 'varchar(10)', comment: 'Pass (G3>=10), Fail (G3<10)' },
    ],
  },
  {
    name: 'student_risk_analysis',
    type: 'TABLE',
    description: 'Predictive risk scoring output generated by ML model / Athena SQL pipeline',
    columns: [
      { name: 'student_id', type: 'varchar(20)' },
      { name: 'risk_level', type: 'varchar(20)', comment: 'Low Risk, Moderate Risk, High Risk' },
      { name: 'risk_factors', type: 'array<string>' },
      { name: 'intervention_priority', type: 'varchar(10)' },
    ],
  },
  {
    name: 'student_dashboard_metrics',
    type: 'VIEW',
    description: 'Aggregated KPI metrics for executive dashboard overview',
    sqlDefinition: `CREATE OR REPLACE VIEW student_dashboard_metrics AS
SELECT 
    COUNT(*) AS total_students,
    ROUND(AVG(g1), 2) AS avg_g1,
    ROUND(AVG(g2), 2) AS avg_g2,
    ROUND(AVG(g3), 2) AS avg_g3,
    ROUND(AVG(absences), 2) AS avg_absences,
    ROUND(AVG(studytime), 2) AS avg_study_time,
    COUNT(CASE WHEN g3 >= 10 THEN 1 END) AS pass_count,
    COUNT(CASE WHEN g3 < 10 THEN 1 END) AS fail_count,
    ROUND(COUNT(CASE WHEN g3 >= 10 THEN 1 END) * 100.0 / COUNT(*), 2) AS pass_rate,
    COUNT(CASE WHEN g3 >= 15 THEN 1 END) AS high_performers,
    COUNT(CASE WHEN g3 < 10 THEN 1 END) AS at_risk_students
FROM "student_data_lake_db"."student_analytics";`,
    columns: [
      { name: 'total_students', type: 'bigint' },
      { name: 'avg_g1', type: 'double' },
      { name: 'avg_g2', type: 'double' },
      { name: 'avg_g3', type: 'double' },
      { name: 'avg_absences', type: 'double' },
      { name: 'avg_study_time', type: 'double' },
      { name: 'pass_count', type: 'bigint' },
      { name: 'fail_count', type: 'bigint' },
      { name: 'pass_rate', type: 'double' },
      { name: 'high_performers', type: 'bigint' },
      { name: 'at_risk_students', type: 'bigint' },
    ],
  },
  {
    name: 'student_performance_analysis',
    type: 'VIEW',
    description: 'Dimensional aggregations for school, study time, and risk cross-tabulation',
    sqlDefinition: `CREATE OR REPLACE VIEW student_performance_analysis AS
SELECT 
    school,
    studytime,
    absence_group,
    performance_level,
    risk_level,
    COUNT(*) AS student_count,
    ROUND(AVG(g3), 2) AS avg_final_grade
FROM "student_data_lake_db"."student_analytics" a
JOIN "student_data_lake_db"."student_risk_analysis" r ON a.student_id = r.student_id
GROUP BY school, studytime, absence_group, performance_level, risk_level;`,
    columns: [
      { name: 'school', type: 'varchar' },
      { name: 'studytime', type: 'int' },
      { name: 'absence_group', type: 'varchar' },
      { name: 'performance_level', type: 'varchar' },
      { name: 'risk_level', type: 'varchar' },
      { name: 'student_count', type: 'bigint' },
      { name: 'avg_final_grade', type: 'double' },
    ],
  },
];

// Live AWS API Base URL
const API_BASE_URL = (
  import.meta.env.VITE_API_BASE_URL ||
  'https://1a1fnoowu1.execute-api.ap-southeast-2.amazonaws.com'
).replace(/\/$/, '');

export class StudentDataService {
  private static instance: StudentDataService;
  private sessionStudents: Student[] = [];

  private constructor() {}

  public static getInstance(): StudentDataService {
    if (!StudentDataService.instance) {
      StudentDataService.instance = new StudentDataService();
    }
    return StudentDataService.instance;
  }

  /**
   * Fetch student records from real AWS API Gateway / Athena.
   * Throws an error on failure without falling back to mock records.
   */
  public async getStudents(filters?: FilterState): Promise<Student[]> {
    try {
      const queryParams = new URLSearchParams();

      if (filters) {
        if (filters.school && filters.school !== 'all') queryParams.append('school', filters.school);
        if (filters.sex && filters.sex !== 'all') queryParams.append('sex', filters.sex);
        if (filters.studytime && filters.studytime !== 'all') queryParams.append('studytime', filters.studytime);
        if (filters.performance_level && filters.performance_level !== 'all') {
          queryParams.append('performance_level', filters.performance_level);
        }
        if (filters.risk_level && filters.risk_level !== 'all') {
          queryParams.append('risk_level', filters.risk_level);
        }
        if (filters.absence_group && filters.absence_group !== 'all') {
          queryParams.append('absence_group', filters.absence_group);
        }
      }

      // Cache-busting timestamp to prevent browser HTTP caching (no CORS-triggering headers)
      queryParams.append('_t', Date.now().toString());

      const queryString = queryParams.toString();
      const url = `${API_BASE_URL}/api/students${queryString ? `?${queryString}` : ''}`;

      const response = await fetch(url, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (!response.ok) {
        const errText = await response.text().catch(() => '');
        throw new Error(`AWS API Gateway returned status ${response.status} (${response.statusText}): ${errText}`);
      }

      const data = await response.json();
      const rawList = data.students || [];

      // Map Athena database records into frontend Student interface.
      // Real student records from S3/API (e.g. STU-1000, STU-1001) preserve their exact IDs.
      // Historical Athena baseline records without an ID receive unique HISTORICAL-xxxx synthetic IDs
      // to ensure zero collisions with real student IDs during deduplication.
      let historicalCounter = 1;
      let mappedStudents: Student[] = rawList.map((row: any) => {
        const g1 = Number(row.g1 ?? row.G1 ?? 0);
        const g2 = Number(row.g2 ?? row.G2 ?? 0);
        const g3 = Number(row.g3 ?? row.G3 ?? 0);
        const absences = Number(row.absences ?? 0);
        const studytime = Number(row.studytime ?? 2);
        const failures = Number(row.failures ?? 0);
        const studentId =
          row.student_id ||
          row.id ||
          `HISTORICAL-${String(historicalCounter++).padStart(4, '0')}`;

        const performance_level =
          row.performance_level || (g3 >= 15 ? 'High' : g3 < 10 ? 'Low' : 'Medium');

        const absence_group =
          row.absence_group ||
          (absences >= 10 ? 'High (10+)' : absences >= 5 ? 'Moderate (5-9)' : 'Low (0-4)');

        let risk_level = row.risk_level;
        if (!risk_level) {
          if (failures >= 2 || (failures === 1 && (g1 + g2) <= 6)) {
            risk_level = 'High Risk';
          } else if (failures === 0 && g1 >= 11 && g2 >= 10 && absences <= 9) {
            risk_level = 'Low Risk';
          } else {
            risk_level = 'Moderate Risk';
          }
        }

        const pass_status = row.pass_status || (g3 >= 10 ? 'Pass' : 'Fail');

        return {
          id: studentId,
          school: row.school === 'MS' ? 'MS' : 'GP',
          sex: row.sex === 'M' ? 'M' : 'F',
          age: Number(row.age ?? 17),
          studytime: (studytime >= 1 && studytime <= 4 ? studytime : 2) as 1 | 2 | 3 | 4,
          failures: failures,
          schoolsup: (row.schoolsup === 'yes' ? 'yes' : 'no') as 'yes' | 'no',
          famsup: (row.famsup === 'no' ? 'no' : 'yes') as 'yes' | 'no',
          paid: (row.paid === 'yes' ? 'yes' : 'no') as 'yes' | 'no',
          activities: (row.activities === 'no' ? 'no' : 'yes') as 'yes' | 'no',
          higher: (row.higher === 'no' ? 'no' : 'yes') as 'yes' | 'no',
          internet: (row.internet === 'no' ? 'no' : 'yes') as 'yes' | 'no',
          famrel: Number(row.famrel ?? 4),
          freetime: Number(row.freetime ?? 3),
          goout: Number(row.goout ?? 3),
          health: Number(row.health ?? 4),
          absences: absences,
          G1: g1,
          G2: g2,
          G3: g3,
          performance_level,
          absence_group,
          risk_level,
          pass_status,
        };
      });

      // Merge any newly added students from this active session (deduplicated by ID)
      const studentMap = new Map<string, Student>();
      // Session students first (so newly added are prioritized and at the top)
      this.sessionStudents.forEach((s) => studentMap.set(s.id, s));
      // API students
      mappedStudents.forEach((s) => {
        if (!studentMap.has(s.id)) {
          studentMap.set(s.id, s);
        }
      });
      let combinedStudents = Array.from(studentMap.values());

      // Apply filters if provided
      if (filters) {
        if (filters.school && filters.school !== 'all') {
          combinedStudents = combinedStudents.filter((s) => s.school === filters.school);
        }
        if (filters.sex && filters.sex !== 'all') {
          combinedStudents = combinedStudents.filter((s) => s.sex === filters.sex);
        }
        if (filters.studytime && filters.studytime !== 'all') {
          combinedStudents = combinedStudents.filter((s) => String(s.studytime) === filters.studytime);
        }
        if (filters.performance_level && filters.performance_level !== 'all') {
          combinedStudents = combinedStudents.filter((s) => s.performance_level === filters.performance_level);
        }
        if (filters.risk_level && filters.risk_level !== 'all') {
          combinedStudents = combinedStudents.filter((s) => s.risk_level === filters.risk_level);
        }
        if (filters.absence_group && filters.absence_group !== 'all') {
          combinedStudents = combinedStudents.filter((s) => s.absence_group === filters.absence_group);
        }
      }

      // Apply client-side text search if provided
      if (filters?.searchQuery && filters.searchQuery.trim() !== '') {
        const q = filters.searchQuery.toLowerCase().trim();
        combinedStudents = combinedStudents.filter((s) => {
          return (
            s.id.toLowerCase().includes(q) ||
            s.school.toLowerCase().includes(q) ||
            String(s.age).includes(q) ||
            String(s.G3).includes(q)
          );
        });
      }

      return combinedStudents;
    } catch (err: any) {
      console.error('[studentDataService.getStudents] API Gateway request error:', err);
      throw err;
    }
  }

  /**
   * Fetch aggregated KPI metrics over active dataset
   */
  public async getMetrics(filteredStudents?: Student[]): Promise<DashboardMetrics> {
    return calculateMetrics(filteredStudents || []);
  }

  /**
   * Add a new student record (persists to S3 data lake via AWS API Gateway)
   */
  public async addStudent(student: Student): Promise<Student> {
    console.log('[studentDataService.addStudent] Invoked for student ID:', student.id);
    console.log('[studentDataService.addStudent] API_BASE_URL:', API_BASE_URL);

    const fullUrl = `${API_BASE_URL}/api/students`;
    console.log(`[studentDataService.addStudent] Executing HTTP POST -> ${fullUrl}`);
    console.log('[studentDataService.addStudent] Payload:', student);

    let response: Response;
    try {
      response = await fetch(fullUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(student),
      });
    } catch (networkError: any) {
      console.error('[studentDataService.addStudent] Network request failed completely:', networkError);
      throw new Error(`Network failure calling ${fullUrl}: ${networkError.message || networkError}`);
    }

    console.log(`[studentDataService.addStudent] Response status: ${response.status} ${response.statusText}`);

    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      const msg = errData.message || `Server returned status ${response.status} ${response.statusText}`;
      console.error('[studentDataService.addStudent] API responded with error:', msg, errData);
      throw new Error(msg);
    }

    const data = await response.json();
    console.log('[studentDataService.addStudent] Successful POST response data:', data);
    const created = data.student || student;
    this.sessionStudents = [created, ...this.sessionStudents.filter((s) => s.id !== created.id)];
    return created;
  }

  /**
   * Delete a student record (removes from session; S3 deletion requires backend DELETE endpoint)
   */
  public async deleteStudent(studentId: string): Promise<void> {
    console.log('[studentDataService.deleteStudent] Removing student:', studentId);
    // Remove from session cache
    this.sessionStudents = this.sessionStudents.filter((s) => s.id !== studentId);

    // Attempt to call DELETE API if available
    try {
      const fullUrl = `${API_BASE_URL}/api/students/${encodeURIComponent(studentId)}`;
      const response = await fetch(fullUrl, {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
      });
      if (response.ok) {
        console.log('[studentDataService.deleteStudent] Server deletion successful');
      } else {
        // If DELETE endpoint not available, just do client-side removal
        console.warn('[studentDataService.deleteStudent] Server DELETE not available, removed client-side only');
      }
    } catch {
      // Network error — still remove client-side
      console.warn('[studentDataService.deleteStudent] Network error on DELETE, removed client-side only');
    }
  }

  public getAthenaSchema(): AthenaSchemaObject[] {
    return ATHENA_OBJECTS;
  }
}

export const studentDataService = StudentDataService.getInstance();
