import { Student, DashboardMetrics, FilterState } from '../types/student';
import { MOCK_STUDENTS, calculateMetrics } from '../data/mockStudentData';

export interface AthenaSchemaObject {
  name: string;
  type: 'TABLE' | 'VIEW';
  description: string;
  sqlDefinition?: string;
  columns: { name: string; type: string; comment?: string }[];
}

export const ATHENA_OBJECTS: AthenaSchemaObject[] = [
  {
    name: 'student_raw',
    type: 'TABLE',
    description: 'Raw ingested student records from S3 data lake (CSV/Parquet format)',
    columns: [
      { name: 'school', type: 'varchar(10)', comment: 'School code: GP or MS' },
      { name: 'sex', type: 'varchar(2)', comment: 'Gender: F or M' },
      { name: 'age', type: 'int', comment: 'Student age in years' },
      { name: 'studytime', type: 'int', comment: 'Weekly study time: 1 (<2h) to 4 (>10h)' },
      { name: 'failures', type: 'int', comment: 'Number of past class failures' },
      { name: 'absences', type: 'int', comment: 'Number of school absences' },
      { name: 'G1', type: 'int', comment: 'First period grade (0-20)' },
      { name: 'G2', type: 'int', comment: 'Second period grade (0-20)' },
      { name: 'G3', type: 'int', comment: 'Final grade (0-20)' },
    ],
  },
  {
    name: 'student_analytics',
    type: 'TABLE',
    description: 'Enriched analytical dataset with categorized features and standardized metrics',
    columns: [
      { name: 'student_id', type: 'varchar(20)' },
      { name: 'school', type: 'varchar(10)' },
      { name: 'sex', type: 'varchar(2)' },
      { name: 'age', type: 'int' },
      { name: 'studytime', type: 'int' },
      { name: 'absences', type: 'int' },
      { name: 'G1', type: 'int' },
      { name: 'G2', type: 'int' },
      { name: 'G3', type: 'int' },
      { name: 'performance_level', type: 'varchar(15)', comment: 'High (>=15), Medium (10-14), Low (<10)' },
      { name: 'absence_group', type: 'varchar(20)', comment: 'Low (0-4), Moderate (5-9), High (10+)' },
      { name: 'pass_status', type: 'varchar(10)', comment: 'Pass (G3>=10), Fail (G3<10)' },
    ],
  },
  {
    name: 'student_risk_analysis',
    type: 'TABLE',
    description: 'Predictive risk scoring output generated by ML model / Athena SQL pipeline',
    columns: [
      { name: 'student_id', type: 'varchar(20)' },
      { name: 'risk_level', type: 'varchar(20)', comment: 'Low Risk, Moderate Risk, High Risk' },
      { name: 'risk_factors', type: 'array<string>' },
      { name: 'intervention_priority', type: 'varchar(10)' },
    ],
  },
  {
    name: 'student_dashboard_metrics',
    type: 'VIEW',
    description: 'Aggregated KPI metrics for executive dashboard overview',
    sqlDefinition: `CREATE OR REPLACE VIEW student_dashboard_metrics AS
SELECT 
    COUNT(*) AS total_students,
    ROUND(AVG(g1), 2) AS avg_g1,
    ROUND(AVG(g2), 2) AS avg_g2,
    ROUND(AVG(g3), 2) AS avg_g3,
    ROUND(AVG(absences), 2) AS avg_absences,
    ROUND(AVG(studytime), 2) AS avg_study_time,
    COUNT(CASE WHEN g3 >= 10 THEN 1 END) AS pass_count,
    COUNT(CASE WHEN g3 < 10 THEN 1 END) AS fail_count,
    ROUND(COUNT(CASE WHEN g3 >= 10 THEN 1 END) * 100.0 / COUNT(*), 2) AS pass_rate,
    COUNT(CASE WHEN g3 >= 15 THEN 1 END) AS high_performers,
    COUNT(CASE WHEN g3 < 10 THEN 1 END) AS at_risk_students
FROM "student_data_lake_db"."student_analytics";`,
    columns: [
      { name: 'total_students', type: 'bigint' },
      { name: 'avg_g1', type: 'double' },
      { name: 'avg_g2', type: 'double' },
      { name: 'avg_g3', type: 'double' },
      { name: 'avg_absences', type: 'double' },
      { name: 'avg_study_time', type: 'double' },
      { name: 'pass_count', type: 'bigint' },
      { name: 'fail_count', type: 'bigint' },
      { name: 'pass_rate', type: 'double' },
      { name: 'high_performers', type: 'bigint' },
      { name: 'at_risk_students', type: 'bigint' },
    ],
  },
  {
    name: 'student_performance_analysis',
    type: 'VIEW',
    description: 'Dimensional aggregations for school, study time, and risk cross-tabulation',
    sqlDefinition: `CREATE OR REPLACE VIEW student_performance_analysis AS
SELECT 
    school,
    studytime,
    absence_group,
    performance_level,
    risk_level,
    COUNT(*) AS student_count,
    ROUND(AVG(g3), 2) AS avg_final_grade
FROM "student_data_lake_db"."student_analytics" a
JOIN "student_data_lake_db"."student_risk_analysis" r ON a.student_id = r.student_id
GROUP BY school, studytime, absence_group, performance_level, risk_level;`,
    columns: [
      { name: 'school', type: 'varchar' },
      { name: 'studytime', type: 'int' },
      { name: 'absence_group', type: 'varchar' },
      { name: 'performance_level', type: 'varchar' },
      { name: 'risk_level', type: 'varchar' },
      { name: 'student_count', type: 'bigint' },
      { name: 'avg_final_grade', type: 'double' },
    ],
  },
];

// Configurable API Base URL (defaults to production API Gateway)
const DEFAULT_API_BASE_URL = 'https://1a1fnoowu1.execute-api.ap-southeast-2.amazonaws.com';
const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || DEFAULT_API_BASE_URL).replace(/\/$/, '');

export class StudentDataService {
  private static instance: StudentDataService;
  private fallbackStudents: Student[] = MOCK_STUDENTS;
  private sessionAddedStudents: Student[] = [];

  private constructor() {}

  public static getInstance(): StudentDataService {
    if (!StudentDataService.instance) {
      StudentDataService.instance = new StudentDataService();
    }
    return StudentDataService.instance;
  }

  /**
   * Fetch student records from real AWS API Gateway / Athena if configured,
   * otherwise gracefully fall back to deterministic local mock dataset.
   */
  public async getStudents(filters?: FilterState): Promise<Student[]> {
    if (API_BASE_URL) {
      try {
        const queryParams = new URLSearchParams();

        if (filters) {
          if (filters.school && filters.school !== 'all') queryParams.append('school', filters.school);
          if (filters.sex && filters.sex !== 'all') queryParams.append('sex', filters.sex);
          if (filters.studytime && filters.studytime !== 'all') queryParams.append('studytime', filters.studytime);
          if (filters.performance_level && filters.performance_level !== 'all') {
            queryParams.append('performance_level', filters.performance_level);
          }
          if (filters.risk_level && filters.risk_level !== 'all') {
            queryParams.append('risk_level', filters.risk_level);
          }
          if (filters.absence_group && filters.absence_group !== 'all') {
            queryParams.append('absence_group', filters.absence_group);
          }
        }

        const queryString = queryParams.toString();
        const url = `${API_BASE_URL}/api/students${queryString ? `?${queryString}` : ''}`;

        const response = await fetch(url, {
          method: 'GET',
          headers: { 'Content-Type': 'application/json' },
        });

        if (!response.ok) {
          throw new Error(`API returned status ${response.status}: ${response.statusText}`);
        }

        const data = await response.json();
        const rawList = data.students || [];

        // Map Athena database records into frontend Student interface
        let mappedStudents: Student[] = rawList.map((row: any, idx: number) => {
          const g1 = Number(row.g1 ?? row.G1 ?? 0);
          const g2 = Number(row.g2 ?? row.G2 ?? 0);
          const g3 = Number(row.g3 ?? row.G3 ?? 0);
          const absences = Number(row.absences ?? 0);
          const studytime = Number(row.studytime ?? 2);

          let absence_group: Student['absence_group'] = 'Low (0-4)';
          if (absences >= 10) absence_group = 'High (10+)';
          else if (absences >= 5) absence_group = 'Moderate (5-9)';

          let performance_level: Student['performance_level'] = 'Medium';
          if (g3 >= 15) performance_level = 'High';
          else if (g3 < 10) performance_level = 'Low';

          let risk_level: Student['risk_level'] = (row.risk_level || 'Low Risk') as Student['risk_level'];

          return {
            id: row.student_id || `STU-${String(idx + 1).padStart(4, '0')}`,
            school: (row.school || 'GP') as Student['school'],
            sex: (row.sex || 'F') as Student['sex'],
            age: Number(row.age || 17),
            studytime,
            failures: Number(row.failures || 0),
            schoolsup: row.schoolsup || 'no',
            famsup: row.famsup || 'yes',
            paid: row.paid || 'no',
            activities: row.activities || 'yes',
            higher: row.higher || 'yes',
            internet: row.internet || 'yes',
            famrel: Number(row.famrel || 4),
            freetime: Number(row.freetime || 3),
            goout: Number(row.goout || 3),
            health: Number(row.health || 4),
            absences,
            G1: g1,
            G2: g2,
            G3: g3,
            performance_level: row.performance_level || performance_level,
            absence_group: row.absence_group || absence_group,
            risk_level,
            pass_status: g3 >= 10 ? 'Pass' : 'Fail',
          };
        });

        // Merge newly created session students if Athena query hasn't reindexed them yet
        for (const sessionStu of this.sessionAddedStudents) {
          if (!mappedStudents.some((s) => s.id.toLowerCase() === sessionStu.id.toLowerCase())) {
            mappedStudents.unshift(sessionStu);
          }
        }

        // Apply client-side text search if provided
        if (filters?.searchQuery && filters.searchQuery.trim() !== '') {
          const q = filters.searchQuery.toLowerCase().trim();
          mappedStudents = mappedStudents.filter((student) => {
            return (
              student.id.toLowerCase().includes(q) ||
              student.school.toLowerCase().includes(q) ||
              String(student.age).includes(q) ||
              String(student.G3).includes(q)
            );
          });
        }

        return mappedStudents;
      } catch (err) {
        console.warn('Real Athena API call failed or is unavailable. Falling back to local dataset:', err);
      }
    }

    // Local Fallback Filter Execution
    await new Promise((resolve) => setTimeout(resolve, 50));
    if (!filters) return this.fallbackStudents;

    return this.fallbackStudents.filter((student) => {
      if (filters.school && filters.school !== 'all' && student.school !== filters.school) {
        return false;
      }
      if (filters.sex && filters.sex !== 'all' && student.sex !== filters.sex) {
        return false;
      }
      if (filters.studytime && filters.studytime !== 'all' && String(student.studytime) !== filters.studytime) {
        return false;
      }
      if (filters.performance_level && filters.performance_level !== 'all' && student.performance_level !== filters.performance_level) {
        return false;
      }
      if (filters.risk_level && filters.risk_level !== 'all' && student.risk_level !== filters.risk_level) {
        return false;
      }
      if (filters.absence_group && filters.absence_group !== 'all' && student.absence_group !== filters.absence_group) {
        return false;
      }
      if (filters.searchQuery && filters.searchQuery.trim() !== '') {
        const q = filters.searchQuery.toLowerCase().trim();
        const matchesId = student.id.toLowerCase().includes(q);
        const matchesSchool = student.school.toLowerCase().includes(q);
        const matchesAge = String(student.age).includes(q);
        const matchesG3 = String(student.G3).includes(q);
        if (!matchesId && !matchesSchool && !matchesAge && !matchesG3) {
          return false;
        }
      }
      return true;
    });
  }

  /**
   * Fetch aggregated KPI metrics from Athena or calculate over active dataset
   */
  public async getMetrics(filteredStudents?: Student[]): Promise<DashboardMetrics> {
    const list = filteredStudents || this.fallbackStudents;
    return calculateMetrics(list);
  }

  public getAthenaSchema(): AthenaSchemaObject[] {
    return ATHENA_OBJECTS;
  }

  /**
   * Submit new student record to AWS API Gateway / Athena backend
   */
  public async createStudent(student: Student): Promise<{ success: boolean; message: string; student: Student }> {
    if (API_BASE_URL) {
      const url = `${API_BASE_URL}/api/students`;
      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(student),
      });

      const data = await response.json().catch(() => ({}));

      if (!response.ok) {
        const errorMsg = data.message || data.error || `Server responded with status ${response.status}`;
        throw new Error(errorMsg);
      }

      const createdStudent = data.student || student;
      if (!this.sessionAddedStudents.some((s) => s.id.toLowerCase() === createdStudent.id.toLowerCase())) {
        this.sessionAddedStudents.unshift(createdStudent);
      }
      this.fallbackStudents.unshift(createdStudent);

      return { success: true, message: data.message || 'Student created successfully', student: createdStudent };
    }

    await new Promise((resolve) => setTimeout(resolve, 100));
    if (!this.sessionAddedStudents.some((s) => s.id.toLowerCase() === student.id.toLowerCase())) {
      this.sessionAddedStudents.unshift(student);
    }
    this.fallbackStudents.unshift(student);
    return { success: true, message: 'Student added to local dataset', student };
  }
}

export const studentDataService = StudentDataService.getInstance();
